import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./(component)/nav";
import { AuthProvider } from "./(component)/Auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

       <Navigation/>
       <AuthProvider>
        <div> {children}</div>
        </AuthProvider>
        </body>
    </html>
  );
}
